import { MEALS, type Meal } from "@/lib/startHereCatalog";

export const PLANT_MEALS: Meal[] = [
  {
    id: "tofu-breakfast-wrap",
    name: "Savory tofu breakfast wrap",
    type: "Breakfast",
    cuisine: "American",
    format: "Wraps",
    prepMinutes: 12,
    cost: "low",
    preferenceTags: ["Wraps", "Breakfast foods", "Savory breakfast"],
    searchTags: ["tofu", "breakfast", "wrap", "vegan", "plant based"],
    why: "A savory, protein-forward breakfast without relying on eggs or dairy.",
    ingredients: [
      { name: "Extra-firm tofu", amount: "7 oz", calories: 190, protein: 22, tags: ["tofu", "soy", "plant protein"] },
      { name: "Large flour tortilla", amount: "1", calories: 210, protein: 6, tags: ["wrap", "tortilla", "wheat"] },
      { name: "Peppers + spinach", amount: "1.5 cups", calories: 55, protein: 3, tags: ["vegetables", "pepper", "spinach"] },
      { name: "Salsa", amount: "1/4 cup", calories: 25, protein: 1, tags: ["salsa", "tomato"] },
    ],
  },
  {
    id: "lentil-taco-bowl",
    name: "Lentil taco bowl",
    type: "Lunch",
    cuisine: "Mexican",
    format: "Bowls",
    prepMinutes: 18,
    cost: "low",
    preferenceTags: ["Rice bowls", "Tacos", "Mexican", "Bowls"],
    searchTags: ["lentils", "rice", "beans", "mexican", "vegan", "plant based"],
    why: "A low-cost bowl with familiar taco flavors and a substantial plant-protein base.",
    ingredients: [
      { name: "Cooked lentils", amount: "1 cup", calories: 230, protein: 18, tags: ["lentils", "legumes", "plant protein"] },
      { name: "Cooked rice", amount: "3/4 cup", calories: 155, protein: 3, tags: ["rice"] },
      { name: "Black beans", amount: "1/2 cup", calories: 115, protein: 8, tags: ["beans", "legumes", "plant protein"] },
      { name: "Corn salsa", amount: "1/2 cup", calories: 70, protein: 2, tags: ["corn", "salsa"] },
      { name: "Lettuce + pico", amount: "1 cup", calories: 30, protein: 1, tags: ["vegetables", "tomato"] },
    ],
  },
  {
    id: "tofu-rice-bowl",
    name: "Crispy tofu rice bowl",
    type: "Lunch",
    cuisine: "Asian",
    format: "Bowls",
    prepMinutes: 20,
    cost: "low",
    preferenceTags: ["Rice bowls", "Asian", "Bowls"],
    searchTags: ["tofu", "rice", "asian", "vegan", "plant based"],
    why: "Straightforward rice-bowl structure with tofu as the protein anchor.",
    ingredients: [
      { name: "Extra-firm tofu", amount: "8 oz", calories: 220, protein: 25, tags: ["tofu", "soy", "plant protein"] },
      { name: "Cooked jasmine rice", amount: "1 cup", calories: 205, protein: 4, tags: ["rice"] },
      { name: "Broccoli + carrots", amount: "2 cups", calories: 100, protein: 6, tags: ["vegetables", "broccoli", "carrots"] },
      { name: "Teriyaki-style sauce", amount: "2 tbsp", calories: 55, protein: 1, tags: ["sauce", "soy"] },
    ],
  },
  {
    id: "lentil-marinara-pasta",
    name: "Lentil marinara pasta",
    type: "Dinner",
    cuisine: "Italian",
    format: "Pasta",
    prepMinutes: 22,
    cost: "low",
    preferenceTags: ["Pasta", "Italian"],
    searchTags: ["lentils", "pasta", "marinara", "italian", "vegan", "plant based"],
    why: "A normal pasta dinner with lentils adding protein and staying power.",
    ingredients: [
      { name: "Pasta", amount: "3 oz dry", calories: 310, protein: 11, tags: ["pasta", "wheat"] },
      { name: "Cooked lentils", amount: "3/4 cup", calories: 175, protein: 13, tags: ["lentils", "legumes", "plant protein"] },
      { name: "Marinara", amount: "1 cup", calories: 120, protein: 4, tags: ["tomato", "marinara"] },
      { name: "Spinach", amount: "2 cups", calories: 15, protein: 2, tags: ["vegetables", "spinach"] },
    ],
  },
  {
    id: "chickpea-pasta-bowl",
    name: "Chickpea pesto-style pasta",
    type: "Dinner",
    cuisine: "Italian",
    format: "Pasta",
    prepMinutes: 20,
    cost: "medium",
    preferenceTags: ["Pasta", "Italian"],
    searchTags: ["chickpea", "pasta", "italian", "vegan", "plant based"],
    why: "Higher-protein pasta with bright herbs and vegetables, without dairy being required.",
    ingredients: [
      { name: "Chickpea pasta", amount: "3 oz dry", calories: 300, protein: 17, tags: ["chickpea", "pasta", "legumes", "plant protein"] },
      { name: "White beans", amount: "1/2 cup", calories: 120, protein: 8, tags: ["beans", "legumes", "plant protein"] },
      { name: "Dairy-free basil sauce", amount: "1.5 tbsp", calories: 100, protein: 2, tags: ["basil", "sauce"] },
      { name: "Cherry tomatoes + spinach", amount: "2 cups", calories: 50, protein: 3, tags: ["tomato", "spinach", "vegetables"] },
    ],
  },
  {
    id: "soy-berry-smoothie",
    name: "Berry soy protein smoothie",
    type: "Snack",
    cuisine: "American",
    format: "Smoothies",
    prepMinutes: 5,
    cost: "low",
    preferenceTags: ["Smoothies"],
    searchTags: ["smoothie", "soy", "berries", "banana", "vegan", "plant based"],
    why: "An easy protein add-on when another full meal sounds like too much food.",
    ingredients: [
      { name: "Unsweetened soy milk", amount: "1.5 cups", calories: 120, protein: 12, tags: ["soy", "plant protein"] },
      { name: "Pea + rice protein powder", amount: "1 scoop", calories: 120, protein: 24, tags: ["protein powder", "plant protein"] },
      { name: "Frozen berries", amount: "1 cup", calories: 70, protein: 1, tags: ["berries", "fruit"] },
      { name: "Banana", amount: "1 medium", calories: 105, protein: 1, tags: ["banana", "fruit"] },
    ],
  },
];

export const FLEX_MEALS: Meal[] = [
  {
    id: "smoked-salmon-avocado-toast",
    name: "Smoked salmon avocado toast",
    type: "Breakfast",
    cuisine: "American",
    format: "Plates",
    prepMinutes: 8,
    cost: "high",
    preferenceTags: ["Salmon", "Breakfast foods", "Savory breakfast"],
    searchTags: ["salmon", "smoked salmon", "avocado", "toast", "breakfast"],
    why: "A quick savory breakfast when eggs are not what you want.",
    ingredients: [
      { name: "Whole grain toast", amount: "2 slices", calories: 180, protein: 8, tags: ["bread", "toast", "wheat"] },
      { name: "Smoked salmon", amount: "4 oz", calories: 140, protein: 20, tags: ["salmon", "fish"] },
      { name: "Avocado", amount: "1/2 medium", calories: 120, protein: 2, tags: ["avocado"] },
      { name: "Low-fat cottage cheese", amount: "1/2 cup", calories: 90, protein: 13, tags: ["dairy", "cottage cheese"] },
    ],
  },
  {
    id: "egg-breakfast-burrito",
    name: "Egg & turkey breakfast burrito",
    type: "Breakfast",
    cuisine: "Mexican",
    format: "Wraps",
    prepMinutes: 14,
    cost: "medium",
    preferenceTags: ["Eggs", "Turkey", "Wraps", "Breakfast foods"],
    searchTags: ["egg", "turkey", "breakfast", "burrito", "wrap", "mexican"],
    why: "A bigger savory breakfast that still feels like normal food.",
    ingredients: [
      { name: "Eggs", amount: "2 large", calories: 140, protein: 12, tags: ["egg", "eggs"] },
      { name: "Egg whites", amount: "1/2 cup", calories: 60, protein: 13, tags: ["egg", "eggs"] },
      { name: "Lean ground turkey", amount: "3 oz cooked", calories: 150, protein: 21, tags: ["turkey"] },
      { name: "Large flour tortilla", amount: "1", calories: 210, protein: 6, tags: ["wrap", "tortilla", "wheat"] },
      { name: "Salsa", amount: "1/4 cup", calories: 25, protein: 1, tags: ["salsa", "tomato"] },
    ],
  },
  {
    id: "cottage-fruit-crunch",
    name: "Cottage cheese fruit crunch bowl",
    type: "Breakfast",
    cuisine: "American",
    format: "Bowls",
    prepMinutes: 4,
    cost: "low",
    preferenceTags: ["Breakfast foods", "Bowls"],
    searchTags: ["cottage cheese", "fruit", "berries", "granola", "breakfast"],
    why: "A no-cook breakfast with a lot of protein and a different texture from yogurt.",
    ingredients: [
      { name: "Low-fat cottage cheese", amount: "1.5 cups", calories: 270, protein: 39, tags: ["dairy", "cottage cheese"] },
      { name: "Berries", amount: "1 cup", calories: 70, protein: 1, tags: ["fruit", "berries"] },
      { name: "Granola", amount: "1/4 cup", calories: 130, protein: 3, tags: ["granola", "oats"] },
      { name: "Honey", amount: "1 tsp", calories: 20, protein: 0, tags: ["honey"] },
    ],
  },
  {
    id: "chicken-fajita-tacos",
    name: "Chicken fajita tacos",
    type: "Lunch",
    cuisine: "Mexican",
    format: "Tacos",
    prepMinutes: 18,
    cost: "medium",
    preferenceTags: ["Chicken", "Tacos", "Mexican"],
    searchTags: ["chicken", "tacos", "fajita", "mexican", "salsa"],
    why: "A taco option for when another rice bowl sounds repetitive.",
    ingredients: [
      { name: "Grilled chicken breast", amount: "5 oz", calories: 235, protein: 44, tags: ["chicken"] },
      { name: "Corn tortillas", amount: "3 small", calories: 180, protein: 5, tags: ["taco", "tortilla", "corn"] },
      { name: "Fajita vegetables", amount: "1.5 cups", calories: 90, protein: 3, tags: ["vegetables", "peppers", "onion"] },
      { name: "Salsa", amount: "1/3 cup", calories: 30, protein: 1, tags: ["salsa", "tomato"] },
      { name: "Avocado", amount: "1/3 medium", calories: 80, protein: 1, tags: ["avocado"] },
    ],
  },
  {
    id: "salmon-sushi-bowl",
    name: "Salmon sushi-style rice bowl",
    type: "Lunch",
    cuisine: "Asian",
    format: "Bowls",
    prepMinutes: 15,
    cost: "high",
    preferenceTags: ["Salmon", "Rice bowls", "Asian", "Bowls"],
    searchTags: ["salmon", "sushi", "rice", "bowl", "asian", "cucumber"],
    why: "A cooler, lighter-feeling rice bowl when you want something closer to sushi flavors.",
    ingredients: [
      { name: "Cooked salmon", amount: "5 oz", calories: 290, protein: 32, tags: ["salmon", "fish"] },
      { name: "Cooked sushi rice", amount: "1 cup", calories: 240, protein: 4, tags: ["rice", "sushi"] },
      { name: "Cucumber + carrots", amount: "1.5 cups", calories: 55, protein: 2, tags: ["vegetables", "cucumber", "carrots"] },
      { name: "Shelled edamame", amount: "1/2 cup", calories: 100, protein: 9, tags: ["soy", "edamame", "plant protein"] },
      { name: "Light soy-ginger sauce", amount: "2 tbsp", calories: 40, protein: 1, tags: ["soy", "sauce"] },
    ],
  },
  {
    id: "grilled-chicken-sandwich",
    name: "Grilled chicken avocado sandwich",
    type: "Lunch",
    cuisine: "American",
    format: "Sandwiches",
    prepMinutes: 10,
    cost: "medium",
    preferenceTags: ["Chicken", "Sandwiches"],
    searchTags: ["chicken", "sandwich", "avocado", "bread"],
    why: "A straightforward handheld lunch that does not feel like meal prep in a bowl.",
    ingredients: [
      { name: "Grilled chicken breast", amount: "5 oz", calories: 235, protein: 44, tags: ["chicken"] },
      { name: "Whole grain roll", amount: "1", calories: 220, protein: 8, tags: ["bread", "wheat", "sandwich"] },
      { name: "Avocado", amount: "1/3 medium", calories: 80, protein: 1, tags: ["avocado"] },
      { name: "Lettuce + tomato", amount: "1 serving", calories: 20, protein: 1, tags: ["vegetables", "tomato"] },
    ],
  },
  {
    id: "turkey-burger-plate",
    name: "Turkey burger & potato plate",
    type: "Dinner",
    cuisine: "American",
    format: "Plates",
    prepMinutes: 22,
    cost: "medium",
    preferenceTags: ["Turkey", "Plates"],
    searchTags: ["turkey", "burger", "potato", "fries", "american"],
    why: "A burger-style dinner that still has an easy protein anchor and simple sides.",
    ingredients: [
      { name: "Lean turkey burger", amount: "6 oz cooked", calories: 300, protein: 42, tags: ["turkey", "burger"] },
      { name: "Whole grain burger bun", amount: "1", calories: 180, protein: 7, tags: ["bread", "wheat", "burger"] },
      { name: "Roasted potatoes", amount: "8 oz", calories: 175, protein: 5, tags: ["potato"] },
      { name: "Side salad", amount: "2 cups", calories: 45, protein: 2, tags: ["vegetables", "salad"] },
    ],
  },
  {
    id: "chicken-parm-pasta",
    name: "Chicken parmesan pasta",
    type: "Dinner",
    cuisine: "Italian",
    format: "Pasta",
    prepMinutes: 28,
    cost: "medium",
    preferenceTags: ["Chicken", "Pasta", "Italian"],
    searchTags: ["chicken", "parmesan", "chicken parm", "pasta", "italian", "marinara"],
    why: "A familiar comfort-food dinner instead of pretending your plan needs to be plain chicken and rice.",
    ingredients: [
      { name: "Breaded chicken cutlet", amount: "5 oz cooked", calories: 320, protein: 38, tags: ["chicken", "wheat"] },
      { name: "Pasta", amount: "2 oz dry", calories: 210, protein: 7, tags: ["pasta", "wheat"] },
      { name: "Marinara", amount: "3/4 cup", calories: 90, protein: 3, tags: ["tomato", "marinara"] },
      { name: "Mozzarella + parmesan", amount: "1.5 oz", calories: 140, protein: 10, tags: ["dairy", "cheese", "mozzarella", "parmesan"] },
    ],
  },
  {
    id: "beef-stir-fry",
    name: "Beef stir-fry rice plate",
    type: "Dinner",
    cuisine: "Asian",
    format: "Plates",
    prepMinutes: 20,
    cost: "high",
    preferenceTags: ["Steak", "Asian", "Plates"],
    searchTags: ["beef", "steak", "stir fry", "rice", "asian", "vegetables"],
    why: "A higher-flavor beef dinner with vegetables and rice in a different format from a taco bowl.",
    ingredients: [
      { name: "Lean beef strips", amount: "5 oz cooked", calories: 285, protein: 39, tags: ["beef", "steak"] },
      { name: "Cooked jasmine rice", amount: "1 cup", calories: 205, protein: 4, tags: ["rice"] },
      { name: "Stir-fry vegetables", amount: "2 cups", calories: 100, protein: 5, tags: ["vegetables", "broccoli", "peppers"] },
      { name: "Soy-ginger sauce", amount: "2 tbsp", calories: 55, protein: 1, tags: ["soy", "sauce"] },
    ],
  },
  {
    id: "shrimp-taco-bowl",
    name: "Shrimp taco bowl",
    type: "Dinner",
    cuisine: "Mexican",
    format: "Bowls",
    prepMinutes: 16,
    cost: "medium",
    preferenceTags: ["Rice bowls", "Tacos", "Mexican", "Bowls"],
    searchTags: ["shrimp", "shellfish", "rice", "taco", "mexican", "bowl"],
    why: "A lighter seafood option with the same familiar taco flavors.",
    ingredients: [
      { name: "Cooked shrimp", amount: "7 oz", calories: 200, protein: 42, tags: ["shrimp", "shellfish", "seafood"] },
      { name: "Cooked rice", amount: "3/4 cup", calories: 155, protein: 3, tags: ["rice"] },
      { name: "Black beans", amount: "1/2 cup", calories: 115, protein: 8, tags: ["beans"] },
      { name: "Corn salsa", amount: "1/2 cup", calories: 70, protein: 2, tags: ["corn", "salsa"] },
      { name: "Lettuce + pico", amount: "1 cup", calories: 30, protein: 1, tags: ["vegetables", "tomato"] },
    ],
  },
  {
    id: "chocolate-yogurt-bowl",
    name: "Chocolate berry yogurt bowl",
    type: "Snack",
    cuisine: "American",
    format: "Bowls",
    prepMinutes: 4,
    cost: "low",
    preferenceTags: ["Greek yogurt", "Bowls"],
    searchTags: ["greek yogurt", "chocolate", "berries", "snack", "dessert"],
    why: "A sweet snack option that still contributes meaningful protein.",
    ingredients: [
      { name: "Nonfat Greek yogurt", amount: "1.25 cups", calories: 160, protein: 28, tags: ["dairy", "greek yogurt"] },
      { name: "Cocoa powder", amount: "1 tbsp", calories: 12, protein: 1, tags: ["cocoa", "chocolate"] },
      { name: "Berries", amount: "1 cup", calories: 70, protein: 1, tags: ["fruit", "berries"] },
      { name: "Granola", amount: "1/4 cup", calories: 130, protein: 3, tags: ["granola", "oats"] },
    ],
  },
];

export const ALL_MEALS: Meal[] = [...MEALS, ...PLANT_MEALS, ...FLEX_MEALS];
