import { MEALS, type Meal } from "@/lib/startHereCatalog";

export const PLANT_MEALS: Meal[] = [
  {
    id: "tofu-breakfast-wrap",
    name: "Savory tofu breakfast wrap",
    type: "Breakfast",
    cuisine: "American",
    format: "Wraps",
    prepMinutes: 12,
    cost: "low",
    preferenceTags: ["Wraps", "Breakfast foods", "Savory breakfast"],
    searchTags: ["tofu", "breakfast", "wrap", "vegan", "plant based"],
    why: "A savory, protein-forward breakfast without relying on eggs or dairy.",
    ingredients: [
      { name: "Extra-firm tofu", amount: "7 oz", calories: 190, protein: 22, tags: ["tofu", "soy", "plant protein"] },
      { name: "Large flour tortilla", amount: "1", calories: 210, protein: 6, tags: ["wrap", "tortilla", "wheat"] },
      { name: "Peppers + spinach", amount: "1.5 cups", calories: 55, protein: 3, tags: ["vegetables", "pepper", "spinach"] },
      { name: "Salsa", amount: "1/4 cup", calories: 25, protein: 1, tags: ["salsa", "tomato"] },
    ],
  },
  {
    id: "lentil-taco-bowl",
    name: "Lentil taco bowl",
    type: "Lunch",
    cuisine: "Mexican",
    format: "Bowls",
    prepMinutes: 18,
    cost: "low",
    preferenceTags: ["Rice bowls", "Tacos", "Mexican", "Bowls"],
    searchTags: ["lentils", "rice", "beans", "mexican", "vegan", "plant based"],
    why: "A low-cost bowl with familiar taco flavors and a substantial plant-protein base.",
    ingredients: [
      { name: "Cooked lentils", amount: "1 cup", calories: 230, protein: 18, tags: ["lentils", "legumes", "plant protein"] },
      { name: "Cooked rice", amount: "3/4 cup", calories: 155, protein: 3, tags: ["rice"] },
      { name: "Black beans", amount: "1/2 cup", calories: 115, protein: 8, tags: ["beans", "legumes", "plant protein"] },
      { name: "Corn salsa", amount: "1/2 cup", calories: 70, protein: 2, tags: ["corn", "salsa"] },
      { name: "Lettuce + pico", amount: "1 cup", calories: 30, protein: 1, tags: ["vegetables", "tomato"] },
    ],
  },
  {
    id: "tofu-rice-bowl",
    name: "Crispy tofu rice bowl",
    type: "Lunch",
    cuisine: "Asian",
    format: "Bowls",
    prepMinutes: 20,
    cost: "low",
    preferenceTags: ["Rice bowls", "Asian", "Bowls"],
    searchTags: ["tofu", "rice", "asian", "vegan", "plant based"],
    why: "Straightforward rice-bowl structure with tofu as the protein anchor.",
    ingredients: [
      { name: "Extra-firm tofu", amount: "8 oz", calories: 220, protein: 25, tags: ["tofu", "soy", "plant protein"] },
      { name: "Cooked jasmine rice", amount: "1 cup", calories: 205, protein: 4, tags: ["rice"] },
      { name: "Broccoli + carrots", amount: "2 cups", calories: 100, protein: 6, tags: ["vegetables", "broccoli", "carrots"] },
      { name: "Teriyaki-style sauce", amount: "2 tbsp", calories: 55, protein: 1, tags: ["sauce", "soy"] },
    ],
  },
  {
    id: "lentil-marinara-pasta",
    name: "Lentil marinara pasta",
    type: "Dinner",
    cuisine: "Italian",
    format: "Pasta",
    prepMinutes: 22,
    cost: "low",
    preferenceTags: ["Pasta", "Italian"],
    searchTags: ["lentils", "pasta", "marinara", "italian", "vegan", "plant based"],
    why: "A normal pasta dinner with lentils adding protein and staying power.",
    ingredients: [
      { name: "Pasta", amount: "3 oz dry", calories: 310, protein: 11, tags: ["pasta", "wheat"] },
      { name: "Cooked lentils", amount: "3/4 cup", calories: 175, protein: 13, tags: ["lentils", "legumes", "plant protein"] },
      { name: "Marinara", amount: "1 cup", calories: 120, protein: 4, tags: ["tomato", "marinara"] },
      { name: "Spinach", amount: "2 cups", calories: 15, protein: 2, tags: ["vegetables", "spinach"] },
    ],
  },
  {
    id: "chickpea-pasta-bowl",
    name: "Chickpea pesto-style pasta",
    type: "Dinner",
    cuisine: "Italian",
    format: "Pasta",
    prepMinutes: 20,
    cost: "medium",
    preferenceTags: ["Pasta", "Italian"],
    searchTags: ["chickpea", "pasta", "italian", "vegan", "plant based"],
    why: "Higher-protein pasta with bright herbs and vegetables, without dairy being required.",
    ingredients: [
      { name: "Chickpea pasta", amount: "3 oz dry", calories: 300, protein: 17, tags: ["chickpea", "pasta", "legumes", "plant protein"] },
      { name: "White beans", amount: "1/2 cup", calories: 120, protein: 8, tags: ["beans", "legumes", "plant protein"] },
      { name: "Dairy-free basil sauce", amount: "1.5 tbsp", calories: 100, protein: 2, tags: ["basil", "sauce"] },
      { name: "Cherry tomatoes + spinach", amount: "2 cups", calories: 50, protein: 3, tags: ["tomato", "spinach", "vegetables"] },
    ],
  },
  {
    id: "soy-berry-smoothie",
    name: "Berry soy protein smoothie",
    type: "Snack",
    cuisine: "American",
    format: "Smoothies",
    prepMinutes: 5,
    cost: "low",
    preferenceTags: ["Smoothies"],
    searchTags: ["smoothie", "soy", "berries", "banana", "vegan", "plant based"],
    why: "An easy protein add-on when another full meal sounds like too much food.",
    ingredients: [
      { name: "Unsweetened soy milk", amount: "1.5 cups", calories: 120, protein: 12, tags: ["soy", "plant protein"] },
      { name: "Pea + rice protein powder", amount: "1 scoop", calories: 120, protein: 24, tags: ["protein powder", "plant protein"] },
      { name: "Frozen berries", amount: "1 cup", calories: 70, protein: 1, tags: ["berries", "fruit"] },
      { name: "Banana", amount: "1 medium", calories: 105, protein: 1, tags: ["banana", "fruit"] },
    ],
  },
];

export const ALL_MEALS: Meal[] = [...MEALS, ...PLANT_MEALS];
