import { EXERCISES as CORE_EXERCISES, type Exercise } from "@/lib/startHereCatalog";

/**
 * Additional audited movement options used by the adaptive workout builder.
 *
 * The starter catalog intentionally began small. The weekly planner now needs
 * enough distinct choices to create A/B sessions for gym, dumbbell, and
 * household-equipment users without pretending every exercise fits every
 * environment. Cues stay deliberately short and conservative.
 */
export const EXTRA_EXERCISES: Exercise[] = [
  {
    id: "lat-pulldown",
    name: "Lat pulldown",
    pattern: "pull",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Back", "Biceps"],
    cue: "Pull the bar toward your upper chest while keeping your ribs stacked and shoulders away from your ears.",
    alternativeIds: ["seated-row", "chest-supported-row", "band-row"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine shoulder press",
    pattern: "push",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Shoulders", "Triceps"],
    cue: "Set the seat so the handles begin around shoulder height and press without shrugging.",
    alternativeIds: ["seated-dumbbell-press", "machine-chest-press", "incline-pushup"],
  },
  {
    id: "incline-machine-press",
    name: "Incline machine press",
    pattern: "push",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Chest", "Shoulders", "Triceps"],
    cue: "Keep your upper back supported and stop the handles where your shoulders still feel comfortable.",
    alternativeIds: ["machine-chest-press", "dumbbell-floor-press", "incline-pushup"],
  },
  {
    id: "cable-high-row",
    name: "Cable high row",
    pattern: "pull",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Upper back", "Rear shoulders", "Biceps"],
    cue: "Pull toward your upper ribs with a quiet torso and let your shoulder blades move naturally.",
    alternativeIds: ["seated-row", "lat-pulldown", "rear-delt-row"],
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    pattern: "squat",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Quads"],
    cue: "Use a smooth range you can control and avoid snapping the knee into the top position.",
    alternativeIds: ["leg-press", "goblet-squat", "wall-sit"],
  },
  {
    id: "hip-thrust-machine",
    name: "Hip thrust machine",
    pattern: "hinge",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Glutes", "Hamstrings"],
    cue: "Keep your ribs down and finish by squeezing your glutes rather than arching your lower back.",
    alternativeIds: ["glute-bridge", "dumbbell-hip-thrust", "dumbbell-rdl"],
  },
  {
    id: "cable-pull-through",
    name: "Cable pull-through",
    pattern: "hinge",
    equipment: ["gym", "mixed"],
    beginnerFriendly: true,
    stable: false,
    focus: ["Glutes", "Hamstrings"],
    cue: "Let your hips travel back, keep the cable close, then stand tall without leaning backward.",
    alternativeIds: ["dumbbell-rdl", "glute-bridge", "hip-thrust-machine"],
  },
  {
    id: "supported-split-squat",
    name: "Supported split squat",
    pattern: "single-leg",
    equipment: ["gym", "dumbbells", "home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Quads", "Glutes", "Balance"],
    cue: "Keep one hand near support, use a stance that feels steady, and move straight down and up.",
    alternativeIds: ["step-up", "reverse-lunge", "chair-squat"],
  },
  {
    id: "seated-dumbbell-press",
    name: "Seated dumbbell shoulder press",
    pattern: "push",
    equipment: ["dumbbells", "gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Shoulders", "Triceps"],
    cue: "Use back support when available and press the dumbbells without letting your ribs flare up.",
    alternativeIds: ["machine-shoulder-press", "dumbbell-floor-press", "dumbbell-bench"],
  },
  {
    id: "dumbbell-floor-press",
    name: "Dumbbell floor press",
    pattern: "push",
    equipment: ["dumbbells", "home", "gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Chest", "Triceps"],
    cue: "Lower until your upper arms gently meet the floor, then press with your wrists stacked over your elbows.",
    alternativeIds: ["dumbbell-bench", "incline-pushup", "backpack-floor-press"],
  },
  {
    id: "one-arm-dumbbell-row",
    name: "Supported one-arm dumbbell row",
    pattern: "pull",
    equipment: ["dumbbells", "gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Back", "Biceps"],
    cue: "Brace one hand on a stable surface and pull the dumbbell toward your hip without twisting your torso.",
    alternativeIds: ["chest-supported-row", "seated-row", "backpack-row"],
  },
  {
    id: "rear-delt-row",
    name: "Dumbbell rear-delt row",
    pattern: "pull",
    equipment: ["dumbbells", "gym", "mixed"],
    beginnerFriendly: true,
    stable: false,
    focus: ["Upper back", "Rear shoulders"],
    cue: "Use a light load and row with your elbows slightly out while keeping your torso still.",
    alternativeIds: ["cable-high-row", "chest-supported-row", "prone-y-raise"],
  },
  {
    id: "dumbbell-sumo-squat",
    name: "Dumbbell sumo squat",
    pattern: "squat",
    equipment: ["dumbbells", "home", "gym", "mixed"],
    beginnerFriendly: true,
    stable: false,
    focus: ["Quads", "Glutes"],
    cue: "Choose a comfortable wider stance, keep the weight close, and let your knees track with your toes.",
    alternativeIds: ["goblet-squat", "leg-press", "chair-squat"],
  },
  {
    id: "dumbbell-hip-thrust",
    name: "Dumbbell hip thrust",
    pattern: "hinge",
    equipment: ["dumbbells", "home", "gym", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Glutes", "Hamstrings"],
    cue: "Keep the dumbbell secure at your hips and finish each rep with your ribs and pelvis stacked.",
    alternativeIds: ["glute-bridge", "hip-thrust-machine", "dumbbell-rdl"],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase carry",
    pattern: "carry",
    equipment: ["dumbbells", "gym", "home", "mixed"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Core", "Grip", "Posture"],
    cue: "Carry the weight at one side and walk tall without leaning toward or away from it.",
    alternativeIds: ["farmer-carry", "suitcase-hold", "march-hold"],
  },
  {
    id: "wall-pushup",
    name: "Wall push-up",
    pattern: "push",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Chest", "Triceps"],
    cue: "Stand far enough from the wall to feel challenged while keeping your body in one comfortable line.",
    alternativeIds: ["incline-pushup", "backpack-floor-press"],
  },
  {
    id: "backpack-floor-press",
    name: "Backpack floor press",
    pattern: "push",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Chest", "Triceps"],
    cue: "Use a securely closed backpack, keep your elbows comfortable, and stop when your upper arms reach the floor.",
    alternativeIds: ["incline-pushup", "wall-pushup", "dumbbell-floor-press"],
  },
  {
    id: "prone-y-raise",
    name: "Prone Y raise",
    pattern: "pull",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Upper back", "Rear shoulders"],
    cue: "Use no load or a very light one and lift your arms only as high as you can without shrugging.",
    alternativeIds: ["reverse-snow-angel", "band-row", "rear-delt-row"],
  },
  {
    id: "reverse-snow-angel",
    name: "Reverse snow angel",
    pattern: "pull",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Upper back", "Rear shoulders"],
    cue: "Move slowly through a comfortable arc and keep your neck relaxed throughout the rep.",
    alternativeIds: ["prone-y-raise", "band-row", "backpack-row"],
  },
  {
    id: "backpack-row",
    name: "Supported backpack row",
    pattern: "pull",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Back", "Biceps"],
    cue: "Make sure the backpack is closed, brace on a stable surface, and pull it toward your hip without twisting.",
    alternativeIds: ["band-row", "one-arm-dumbbell-row", "reverse-snow-angel"],
  },
  {
    id: "wall-sit",
    name: "Wall sit",
    pattern: "squat",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Quads", "Glutes"],
    cue: "Choose a knee angle you can hold comfortably and keep your whole back supported by the wall.",
    alternativeIds: ["chair-squat", "goblet-squat", "leg-extension"],
  },
  {
    id: "hip-hinge-drill",
    name: "Bodyweight hip hinge",
    pattern: "hinge",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Hamstrings", "Glutes"],
    cue: "Push your hips back toward the wall behind you while keeping your spine long and knees softly bent.",
    alternativeIds: ["glute-bridge", "dumbbell-rdl"],
  },
  {
    id: "side-plank-knees",
    name: "Bent-knee side plank",
    pattern: "core",
    equipment: ["home", "gym", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Core"],
    cue: "Keep your elbow under your shoulder and lift only as high as you can hold without twisting.",
    alternativeIds: ["dead-bug", "pallof-press"],
  },
  {
    id: "suitcase-hold",
    name: "Suitcase hold",
    pattern: "carry",
    equipment: ["home", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Core", "Grip", "Posture"],
    cue: "Hold a secure household weight at one side and stay tall without leaning for 20–30 seconds.",
    alternativeIds: ["suitcase-carry", "march-hold", "farmer-carry"],
  },
  {
    id: "tandem-stand",
    name: "Supported tandem stand",
    pattern: "balance",
    equipment: ["home", "gym", "mixed", "unsure"],
    beginnerFriendly: true,
    stable: true,
    focus: ["Balance"],
    cue: "Stand heel-to-toe near a sturdy support and use as much hand support as you need.",
    alternativeIds: ["march-hold", "step-up"],
  },
];

export const ALL_EXERCISES: Exercise[] = [...CORE_EXERCISES, ...EXTRA_EXERCISES];
